<?php
/**
 * HTML Sitemap - User-friendly sitemap page for visitors.
 *
 * @package FP\SEO
 * @author Francesco Passeri
 * @link https://francescopasseri.com
 */

declare(strict_types=1);

namespace FP\SEO\GEO;

use FP\SEO\Redirects\RedirectsOptions;
use FP\SEO\Utils\PostTypes;

/**
 * Generates a user-friendly HTML sitemap.
 */
class HtmlSitemap {

	/**
	 * Transient key for sitemap cache.
	 */
	private const CACHE_KEY = 'fp_seo_html_sitemap';

	/**
	 * Generate HTML sitemap content.
	 *
	 * @return string HTML content.
	 */
	public function generate(): string {
		$opts   = RedirectsOptions::get_html_sitemap();
		$ttl    = (int) $opts['cache_ttl'];

		$cached = get_transient( self::CACHE_KEY );
		if ( false !== $cached && is_string( $cached ) ) {
			return $cached;
		}

		$html = $this->build_html();
		set_transient( self::CACHE_KEY, $html, $ttl );

		return $html;
	}

	/**
	 * Build full HTML document.
	 *
	 * @return string
	 */
	private function build_html(): string {
		$site_name = get_bloginfo( 'name' );
		$site_desc = get_bloginfo( 'description' );
		$home_url  = home_url( '/' );

		$sections = $this->get_sections();

		ob_start();
		?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><?php echo esc_html( sprintf( /* translators: %s: Site name */ __( 'Sitemap - %s', 'fp-seo-performance' ), $site_name ) ); ?></title>
	<style>
		.fp-seo-sitemap * { box-sizing: border-box; }
		.fp-seo-sitemap { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem 1.5rem; color: #1f2937; line-height: 1.6; }
		.fp-seo-sitemap h1 { font-size: 1.75rem; margin: 0 0 0.5rem; color: #111827; }
		.fp-seo-sitemap .fp-seo-sitemap-desc { color: #6b7280; margin-bottom: 2rem; font-size: 0.95rem; }
		.fp-seo-sitemap-section { margin-bottom: 2.5rem; }
		.fp-seo-sitemap-section h2 { font-size: 1.25rem; margin: 0 0 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid #e5e7eb; color: #374151; }
		.fp-seo-sitemap-list { list-style: none; padding: 0; margin: 0; }
		.fp-seo-sitemap-list li { margin-bottom: 0.5rem; }
		.fp-seo-sitemap-list a { color: #2563eb; text-decoration: none; }
		.fp-seo-sitemap-list a:hover { text-decoration: underline; }
		.fp-seo-sitemap-list .fp-seo-sitemap-date { font-size: 0.8rem; color: #9ca3af; margin-left: 0.5rem; }
		.fp-seo-sitemap-home { display: inline-block; margin-bottom: 2rem; color: #2563eb; text-decoration: none; }
		.fp-seo-sitemap-home:hover { text-decoration: underline; }
		.fp-seo-sitemap-footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; font-size: 0.875rem; color: #9ca3af; }
	</style>
</head>
<body class="fp-seo-sitemap">
	<div class="fp-seo-sitemap">
		<a href="<?php echo esc_url( $home_url ); ?>" class="fp-seo-sitemap-home">&larr; <?php esc_html_e( 'Home', 'fp-seo-performance' ); ?></a>
		<h1><?php echo esc_html( sprintf( /* translators: %s: Site name */ __( 'Sitemap - %s', 'fp-seo-performance' ), $site_name ) ); ?></h1>
		<?php if ( $site_desc ) : ?>
			<p class="fp-seo-sitemap-desc"><?php echo esc_html( $site_desc ); ?></p>
		<?php endif; ?>

		<?php foreach ( $sections as $section ) : ?>
			<section class="fp-seo-sitemap-section">
				<h2><?php echo esc_html( $section['title'] ); ?></h2>
				<ul class="fp-seo-sitemap-list">
					<?php foreach ( $section['items'] as $item ) : ?>
						<li>
							<a href="<?php echo esc_url( $item['url'] ); ?>"><?php echo esc_html( $item['title'] ); ?></a>
							<?php if ( ! empty( $item['date'] ) ) : ?>
								<span class="fp-seo-sitemap-date"><?php echo esc_html( $item['date'] ); ?></span>
							<?php endif; ?>
						</li>
					<?php endforeach; ?>
				</ul>
			</section>
		<?php endforeach; ?>

		<footer class="fp-seo-sitemap-footer">
			<?php
			printf(
				/* translators: %s: Plugin name */
				esc_html__( 'Generated by %s', 'fp-seo-performance' ),
				'<strong>FP SEO Performance</strong>'
			);
			?>
		</footer>
	</div>
</body>
</html>
		<?php
		return (string) ob_get_clean();
	}

	/**
	 * Get sitemap sections (home, pages, posts by type).
	 *
	 * @return array<int, array{title: string, items: array<int, array{url: string, title: string, date?: string}>}>
	 */
	private function get_sections(): array {
		$sections = array();

		// Homepage
		$sections[] = array(
			'title' => __( 'Homepage', 'fp-seo-performance' ),
			'items' => array(
				array(
					'url'   => home_url( '/' ),
					'title' => __( 'Home', 'fp-seo-performance' ),
				),
			),
		);

		$post_types = $this->get_public_post_types();
		$post_types = apply_filters( 'fp_seo_html_sitemap_post_types', $post_types );

		foreach ( $post_types as $post_type ) {
			$items = $this->get_items_for_post_type( $post_type );
			if ( empty( $items ) ) {
				continue;
			}

			$obj   = get_post_type_object( $post_type );
			$label = $obj ? $obj->labels->name : $post_type;

			$sections[] = array(
				'title' => $label,
				'items' => $items,
			);
		}

		return apply_filters( 'fp_seo_html_sitemap_sections', $sections );
	}

	/**
	 * Get public post types for sitemap.
	 *
	 * @return string[]
	 */
	private function get_public_post_types(): array {
		$options = get_option( 'fp_seo_performance', array() );
		$geo     = $options['geo'] ?? array();
		$types   = array();

		if ( ! empty( $geo['post_types'] ) && is_array( $geo['post_types'] ) ) {
			foreach ( $geo['post_types'] as $type => $settings ) {
				if ( ! empty( $settings['in_sitemap'] ) ) {
					$types[] = $type;
				}
			}
		}

		if ( empty( $types ) ) {
			$types = array( 'page', 'post' );
		}

		return array_values( array_unique( $types ) );
	}

	/**
	 * Get items for a post type.
	 *
	 * @param string $post_type Post type slug.
	 * @return array<int, array{url: string, title: string, date?: string}>
	 */
	private function get_items_for_post_type( string $post_type ): array {
		$opts = RedirectsOptions::get_html_sitemap();
		$max  = (int) $opts['max_per_section'];

		$query = new \WP_Query(
			array(
				'post_type'              => $post_type,
				'post_status'            => 'publish',
				'posts_per_page'         => $max,
				'orderby'                => 'modified',
				'order'                  => 'DESC',
				'no_found_rows'          => true,
				'update_post_meta_cache' => false,
				'update_post_term_cache' => false,
				'suppress_filters'       => true,
			)
		);

		$items = array();
		foreach ( $query->posts as $post ) {
			$title = get_the_title( $post );
			if ( empty( $title ) ) {
				$title = __( '(No title)', 'fp-seo-performance' );
			}

			$item = array(
				'url'   => get_permalink( $post ),
				'title' => $title,
			);

			if ( 'post' === $post_type ) {
				$item['date'] = wp_date( get_option( 'date_format' ), strtotime( $post->post_modified ) );
			}

			$items[] = $item;
		}

		return $items;
	}

	/**
	 * Flush sitemap cache.
	 */
	public static function flush_cache(): void {
		delete_transient( self::CACHE_KEY );
	}
}
