<?php
/**
 * LLMs.txt Generator - Creates /llms.txt for LLM guidance
 * 
 * Similar to Yoast's llms.txt, provides a curated list of key content
 * for Large Language Models to better understand and cite your site.
 *
 * @package FP\SEO
 * @author Francesco Passeri
 * @link https://francescopasseri.com
 */

declare(strict_types=1);

namespace FP\SEO\GEO;

use function get_option;
use function get_permalink;
use function get_post;
use function home_url;
use function wp_trim_words;
use function wp_strip_all_tags;
use function apply_filters;

/**
 * Generates llms.txt content
 */
class LlmsTxt {

	/**
	 * Generate llms.txt content
	 *
	 * @return string
	 */
	public function generate(): string {
		// Check cache
		$cached = get_transient( 'fp_seo_geo_llms_txt' );
		if ( false !== $cached && is_string( $cached ) ) {
			return $cached;
		}

		$content = $this->build_llms_txt();

		// Cache for 1 hour (llms.txt should be updated regularly)
		set_transient( 'fp_seo_geo_llms_txt', $content, 3600 );

		return $content;
	}

	/**
	 * Build llms.txt content structure
	 *
	 * @return string
	 */
	private function build_llms_txt(): string {
		$lines = array();

		// Header
		$lines[] = '# llms.txt - Key Content for Large Language Models';
		$lines[] = '# Generated by FP SEO Manager';
		$lines[] = '# This file helps LLMs (ChatGPT, Gemini, Claude, Perplexity) understand your site\'s key content';
		$lines[] = '';

		// Site information
		$site_name = get_bloginfo( 'name' );
		$site_description = get_bloginfo( 'description' );
		$site_url = home_url( '/' );

		$lines[] = '# Site Information';
		$lines[] = 'Site: ' . $site_url;
		if ( $site_name ) {
			$lines[] = 'Name: ' . $site_name;
		}
		if ( $site_description ) {
			$lines[] = 'Description: ' . $site_description;
		}
		$lines[] = '';

		// GEO endpoints
		$lines[] = '# Structured Data Endpoints';
		$lines[] = 'Site JSON: ' . home_url( '/geo/site.json' );
		$lines[] = 'Updates Feed: ' . home_url( '/geo/updates.json' );
		$lines[] = 'GEO Sitemap: ' . home_url( '/geo-sitemap.xml' );
		$lines[] = '';

		// Key content (most important posts/pages)
		$key_content = $this->get_key_content();
		if ( ! empty( $key_content ) ) {
			$lines[] = '# Key Content';
			$lines[] = '# These are the most important pages/posts on this site';
			$lines[] = '';

			foreach ( $key_content as $item ) {
				$lines[] = '## ' . $item['title'];
				$lines[] = 'URL: ' . $item['url'];
				
				// Add JSON endpoint if available
				if ( ! empty( $item['json_url'] ) ) {
					$lines[] = 'JSON: ' . $item['json_url'];
				}
				
				// Add excerpt/description
				if ( ! empty( $item['description'] ) ) {
					$lines[] = 'Description: ' . $item['description'];
				}
				
				// Add last modified date
				if ( ! empty( $item['lastmod'] ) ) {
					$lines[] = 'Last Modified: ' . $item['lastmod'];
				}
				
				$lines[] = '';
			}
		}

		// FAQ Schema content (if available)
		$faq_content = $this->get_faq_content();
		if ( ! empty( $faq_content ) ) {
			$lines[] = '# FAQ Content';
			$lines[] = '# Questions and answers optimized for AI Overview';
			$lines[] = '';

			foreach ( $faq_content as $faq ) {
				$lines[] = '## ' . $faq['title'];
				$lines[] = 'URL: ' . $faq['url'];
				$lines[] = 'FAQ Count: ' . $faq['faq_count'];
				$lines[] = 'Q&A JSON: ' . $faq['qa_url'];
				$lines[] = '';
			}
		}

		// Footer
		$lines[] = '# End of llms.txt';
		$lines[] = '# For more information, visit: ' . $site_url;

		/**
		 * Filter llms.txt lines before output
		 *
		 * @param array<string> $lines Generated lines.
		 */
		$lines = apply_filters( 'fpseo_geo_llms_txt_lines', $lines );
		if ( ! is_array( $lines ) ) {
			$lines = array();
		}

		return implode( "\n", $lines );
	}

	/**
	 * Get key content (most important posts/pages)
	 *
	 * @return array<int, array{title: string, url: string, json_url: string|null, description: string|null, lastmod: string|null}>
	 */
	private function get_key_content(): array {
		$options = get_option( 'fp_seo_performance', array() );
		$geo     = $options['geo'] ?? array();

		// Get enabled post types
		$enabled_types = array();
		if ( ! empty( $geo['post_types'] ) && is_array( $geo['post_types'] ) ) {
			foreach ( $geo['post_types'] as $type => $settings ) {
				if ( ! empty( $settings['expose'] ) ) {
					$enabled_types[] = $type;
				}
			}
		}

		if ( empty( $enabled_types ) ) {
			// Default to post and page
			$enabled_types = array( 'post', 'page' );
		}

		// Get top content by SEO score; fall back to most-recent posts if no scored posts exist.
		$query = new \WP_Query(
			array(
				'post_type'              => $enabled_types,
				'post_status'            => 'publish',
				'posts_per_page'         => 20,
				'orderby'                => 'meta_value_num',
				'meta_key'               => '_fp_seo_performance_score',
				'order'                  => 'DESC',
				'no_found_rows'          => true,
				'update_post_meta_cache' => false,
				'update_post_term_cache' => false,
			)
		);

		// If no posts have an SEO score yet, fall back to the most recent published posts.
		if ( empty( $query->posts ) ) {
			$query = new \WP_Query(
				array(
					'post_type'              => $enabled_types,
					'post_status'            => 'publish',
					'posts_per_page'         => 20,
					'orderby'                => 'date',
					'order'                  => 'DESC',
					'no_found_rows'          => true,
					'update_post_meta_cache' => false,
					'update_post_term_cache' => false,
				)
			);
		}

		$content = array();
		foreach ( $query->posts as $post ) {
			$permalink = get_permalink( $post->ID );
			if ( ! $permalink ) {
				continue;
			}

			$excerpt = wp_trim_words( wp_strip_all_tags( $post->post_content ), 30 );
			if ( empty( $excerpt ) && ! empty( $post->post_excerpt ) ) {
				$excerpt = wp_trim_words( wp_strip_all_tags( $post->post_excerpt ), 30 );
			}

			$content[] = array(
				'title'       => $post->post_title,
				'url'         => $permalink,
				'json_url'    => home_url( '/geo/content/' . $post->ID . '.json' ),
				'description' => $excerpt ?: null,
				'lastmod'     => $post->post_modified,
			);
		}

		return $content;
	}

	/**
	 * Get FAQ content (posts with FAQ Schema)
	 *
	 * @return array<int, array{title: string, url: string, faq_count: int, qa_url: string}>
	 */
	private function get_faq_content(): array {
		$options = get_option( 'fp_seo_performance', array() );
		$geo     = $options['geo'] ?? array();

		// Get enabled post types
		$enabled_types = array();
		if ( ! empty( $geo['post_types'] ) && is_array( $geo['post_types'] ) ) {
			foreach ( $geo['post_types'] as $type => $settings ) {
				if ( ! empty( $settings['expose'] ) ) {
					$enabled_types[] = $type;
				}
			}
		}

		if ( empty( $enabled_types ) ) {
			$enabled_types = array( 'post', 'page' );
		}

		// Get posts with FAQ Schema
		$query = new \WP_Query(
			array(
				'post_type'              => $enabled_types,
				'post_status'            => 'publish',
				'posts_per_page'         => 10, // Top 10 FAQ posts
				'no_found_rows'          => true,
				'update_post_meta_cache' => false,
				'update_post_term_cache' => false,
				'meta_query'             => array(
					array(
						'key'     => '_fp_seo_qa_pairs',
						'compare' => 'EXISTS',
					),
				),
			)
		);

		$faq_content = array();
		foreach ( $query->posts as $post ) {
			$permalink = get_permalink( $post->ID );
			if ( ! $permalink ) {
				continue;
			}

			$qa_pairs = get_post_meta( $post->ID, '_fp_seo_qa_pairs', true );
			$faq_count = is_array( $qa_pairs ) ? count( $qa_pairs ) : 0;

			if ( $faq_count > 0 ) {
				$faq_content[] = array(
					'title'     => $post->post_title,
					'url'       => $permalink,
					'faq_count' => $faq_count,
					'qa_url'    => home_url( '/geo/content/' . $post->ID . '/qa.json' ),
				);
			}
		}

		return $faq_content;
	}
}


